"""
First revision.

Revision ID: 8f273f37ffb4
Revises:
Create Date: 2025-07-23 16:32:21.883336

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f273f37ffb4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "polls",
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("options", sa.JSON(), nullable=False),
        sa.Column("is_open", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("poll_id"),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("user_fullname", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "poll_answers",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("poll_option_id", sa.Integer(), nullable=False),
        sa.Column("poll_answer", sa.Boolean(), nullable=False),
        sa.Column("override_answer", sa.Boolean(), nullable=True),
        sa.Column("driver_id", sa.Integer(), nullable=True),
        sa.Column("return_time", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.poll_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "poll_id", "poll_option_id"),
    )
    op.create_table(
        "poll_reports",
        sa.Column("poll_id", sa.String(), nullable=False),
        sa.Column("chat_id", sa.Integer(), nullable=False),
        sa.Column("message_id", sa.Integer(), nullable=False),
        sa.Column("poll_option_id", sa.Integer(), nullable=True),
        sa.Column("sent_timestamp", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["poll_id"],
            ["polls.poll_id"],
        ),
        sa.PrimaryKeyConstraint("chat_id", "message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("poll_reports")
    op.drop_table("poll_answers")
    op.drop_table("users")
    op.drop_table("polls")
    # ### end Alembic commands ###
