"""
Poll reports tweaks.

Revision ID: cdd49865eadd
Revises: f89b4f3d1f67
Create Date: 2025-07-22 02:00:12.577947

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cdd49865eadd"
down_revision: str | None = "f89b4f3d1f67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("poll_reports", sa.Column("poll_option_id", sa.Integer(), nullable=True))
    op.drop_column("poll_reports", "message_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("poll_reports", sa.Column("message_type", sa.INTEGER(), nullable=False))
    op.drop_column("poll_reports", "poll_option_id")
    # ### end Alembic commands ###
