"""
Added PollAnswer options.

Revision ID: f89b4f3d1f67
Revises: 74143292e64e
Create Date: 2025-07-16 19:50:24.192496

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f89b4f3d1f67"
down_revision: str | None = "74143292e64e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("poll_answers") as batch_op:
        batch_op.add_column(sa.Column("poll_answer", sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column("override_answer", sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column("driver_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("return_time", sa.Integer(), nullable=False))
        batch_op.alter_column("option_id", new_column_name="poll_option_id", existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("poll_answers") as batch_op:
        batch_op.alter_column("poll_option_id", new_column_name="option_id", existing_nullable=False)
        batch_op.drop_column("return_time")
        batch_op.drop_column("driver_id")
        batch_op.drop_column("override_answer")
        batch_op.drop_column("poll_answer")
    # ### end Alembic commands ###
