name: Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    uses: ardubev16/common/.github/workflows/python-test.yaml@main

  prek:
    uses: ardubev16/common/.github/workflows/prek.yaml@main
