name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: ardubev16/common/.github/workflows/python-test.yaml@claude/generic-github-actions-h2gnmq

  prek:
    uses: ardubev16/common/.github/workflows/prek.yaml@claude/generic-github-actions-h2gnmq
